baseURL = "https://pembatikdiy.com"
title = "Sahabat PembaTIK DIY"

# untuk apply temanya
themesDir = "themes"
theme = "temabaru"
copyright = "© {year} | Sahabat PembaTIK DIY"


# Multilingual mode
defaultContentLanguage = "id"
#defaultContentLanguageInSubdir = false # If you use only one language comment this option
#disableLanguages = ["fr", "zh-cn" ,"zh-tw"] # For disable one or more language

# Pagination
paginate = 9
# paginatePath = "page"

# Disqus
disqusShortname = "pembatikdiy"

# Google analytics
googleAnalytics = "UA-205873959-1"

enableRobotsTXT = true

enableEmoji = true

# hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

[related]
    threshold = 0 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "topik"
        weight = 100

[blackfriday]
  hrefTargetBlank = true

[mediaTypes]
  [mediaTypes."application/manifest+json"]
    suffixes = ["json"]
  [mediaTypes."application/rss+xml"]
    suffixes = ["xml", "rss"]

[outputs]
  home = ["HTML", "RSS", "JSON", "MANIFEST"]

[outputFormats]
  [outputFormats.MANIFEST]
    name = "manifest"
    baseName = "manifest"
    mediaType = "application/manifest+json"

[taxonomies]
  topik = "topik"
  kategori = "kategori"

[permalinks]
  artikel = '/:slug'
  tutorial = '/:filename'

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1