email = "bakhtiarsma@gmail.com"
facebook = "bhe.rifai"
github = "mazguru"
gitlab = "mazguru"
twitter = "Bakhtiarrifai14"
instagram = "bherifai"
telegram = "sinaumatematika"
youtube = "UCPqHmSdwMI5ah-1jrn00bBw"
